### ISSUE TITLE
getSignedUrl cannot define expires value

### ISSUE THREAD

**Issue by pinsudasin** [ahmadarif/adonis-drive-minio#1]
I found this code that it doesn't work. The expires value still be default value (600 seconds)
`const url = await Drive.disk('minio', 3600).getSignedUrl('adonis.jpeg')`

But I changed the code to
`const url = await Drive.disk('minio').getSignedUrl('adonis.jpeg', 3600)`

it works for me

**Comment by ahmadarif** [comment]
Sorry for the late reply, and thanks for the feedback. I'll update the README 👍
